
{
  'name': 'Jarvis',
  'author': 'Sundaya IT Team',
  'version': '1.2.0',
  'depends': [
    # 'nama_modul',
    'stock',
    'purchase',
    'contacts',
    'crm',
    'mrp',
    'hr',
    'base',
  ],
  'data': [
    'security/access_role.xml',
    'security/ir.model.access.csv',
    'views/product_template.xml',
    'views/template.xml',
    'views/attachments_tree.xml',
    'views/login.xml',
    'views/edit_inventory.xml',
    'views/contact_template.xml',
    'views/employee_template.xml',
    'views/company_template.xml',
    'views/crm_lead_template.xml',
    'views/mrp_production_views.xml',
    'views/products_view.xml',
    'views/stock_accounts_views.xml',
    'views/stock_warehouse_view.xml',
    'views/purchase_views_inherit.xml',
    'views/res_users_views_inherit.xml',
    'views/mrp_bom_view.xml',
    'report/product_product_templates_inherit.xml',
    'report/product_template_templates_inherit.xml',
    'report/purchase_order_templates_inherit.xml',
    'report/product_reports_inherit.xml',
    'report/mrp_report_bom_structure_inherit.xml',
    'data/sequence.xml',
  ],
  'qweb': [
    'static/src/xml/marker_color.xml',
  ],
  'sequence': 3,
  'auto_install': False,
  'installable': True,
  'application': True,
  'category': 'Enterprise Resource Planning',
  'summary': 'Jarvis System for Sundaya',
  'license': 'OPL-1',
  'website': 'https://github.com/Sundaya-Indo/product_test',
  'description': '-'
}
