from . import product_templates
from . import ir_attachments
from . import employee_template
from . import contact_template
from . import crm_lead_template
from . import mrp_productions
from . import stock_moves
from . import products_products
from . import res_currency_inherit